Disable the cookie too new check
zalora/beego pull request #2
Opened 2017-08-10 08:34 UTC by ibigbug

2017-08-10 12:22 UTC, cdenis95 requested changes

2017-08-10 12:22 UTC, cdenis95 commented on session/sess_utils.go
> +	//if t1 > t2 {
Looks good, but please leave a comment explaining why we are doing this

2017-08-10 12:46 UTC, penmanglewood commented on session/sess_utils.go
>  	//if t1 > t2 {
Do not comment out code. Delete it.

2017-08-11 11:23 UTC, cdenis95 approved these changes

2017-08-11 11:23 UTC, merged